data:
  tokenizer: null
  train_files: HerrHruby/deepscaler_val_256
  val_files: HerrHruby/deepscaler_val_256
  prompt_key: prompt
  reward_fn_key: data_source
  max_prompt_length: 4096
  max_response_length: 2048  # Initial response length.
  train_batch_size: 2
  return_raw_input_ids: False  # This should be set to true when the tokenizer between policy and rm differs
  return_raw_chat: True
  shuffle: True
  filter_overlong_prompts: False # for large-scale dataset, filtering overlong prompts could be timeconsuming. You cat set the filter_overlong_prompts_workers to use multiprocessing to speed up.
  filter_overlong_prompts_workers: 1
  truncation: error
  image_key: images
  prompt_template: null

trainer:
  balance_batch: True
  total_epochs: 1
  total_training_steps: null
  project_name: reasoning_cache
  experiment_name: initial_test
  logger: [ 'console']
  log_val_generations: 3
  nnodes: 1
  n_gpus_per_node: 2
  save_freq: -1
  # auto: find the last ckpt to resume. If can't find, start from scratch
  resume_mode: disable # auto or disable or resume_path if resume_from_path is set
  resume_from_path: null
  val_before_train: True
  test_freq: -1
  critic_warmup: 0
  default_hdfs_dir: null
  del_local_ckpt_after_load: False
  save_dir: /scratch/ianwu
  default_local_dir: ${trainer.save_dir}/checkpoints/${trainer.project_name}/${trainer.experiment_name}
  rollout_data_dir: ${trainer.save_dir}/rollouts/${trainer.project_name}/${trainer.experiment_name}
  max_actor_ckpt_to_keep: 2
  max_critic_ckpt_to_keep: null
  # The timeout for ray worker group to wait for the register center to be ready
  ray_wait_register_center_timeout: 30
  val_only: False
  num_rollouts_to_dump: 4
  dump_every: 1
  
actor_rollout_ref:
  hybrid_engine: True
  model:
    path: Qwen/Qwen3-1.7B
    external_lib: null
    override_config: { }
    enable_gradient_checkpointing: True
    use_remove_padding: False
  actor:
    strategy: fsdp  # This is for backward-compatibility
    ppo_mini_batch_size: 16
    ppo_mini_batch_override: 0 # Split batch into N minibatches. If 0, use ppo_mini_batch_size.
    ppo_micro_batch_size: null # will be deprecated, use ppo_micro_batch_size_per_gpu
    ppo_micro_batch_size_per_gpu: null
    use_dynamic_bsz: False
    ppo_max_token_len_per_gpu: 65536 # n * ${data.max_prompt_length} + ${data.max_response_length}
    grad_clip: 1.0
    only_train_on_positive: False
    remove_truncated: False
    # pg_losses2 = -advantages * torch.clamp(ratio, 1 - cliprange_low, 1 + cliprange_high)
    clip_ratio: 0.2 # default value if clip_ratio_low and clip_ratio_high are not specified
    clip_ratio_low: 0.2
    clip_ratio_high: 0.2
    clip_ratio_c: 3.0 # lower bound of the value for Dual-clip PPO from https://arxiv.org/pdf/1912.09729
    loss_agg_mode: "token-mean" #"token-mean" # / "seq-mean-token-sum" / "seq-mean-token-mean"
    entropy_coeff: 0.0
    use_kl_loss: True # True for GRPO
    use_torch_compile: True # False to disable torch compile
    kl_loss_coef: 0.001 # for grpo
    kl_loss_type: low_var_kl # for grpo
    ppo_epochs: 1
    shuffle: False
    ulysses_sequence_parallel_size: 1 # sp size
    checkpoint:
      contents: ['model', 'optimizer', 'extra']  # with 'hf_model' you can save whole model as hf format, now only use sharded model checkpoint to save space
    optim:
      lr: 1e-6
      lr_warmup_steps: -1 # Prioritized. Negative values mean delegating to lr_warmup_steps_ratio.
      lr_warmup_steps_ratio: 0.0  # the total steps will be injected during runtime
      min_lr_ratio: null   # only useful for warmup with cosine
      warmup_style: constant  # select from constant/cosine
      total_training_steps: -1  # must be override by program
      weight_decay: 0.01
    fsdp_config:
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
      param_offload: False
      optimizer_offload: False
      fsdp_size: -1
    reasoning_cache:
      separate_kl_losses: True
      kl_loss_coef_summary: 0.001
      kl_loss_coef_thinking: 0.0001
  ref:
    fsdp_config:
      param_offload: False
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
    log_prob_micro_batch_size: null # will be deprecated, use log_prob_micro_batch_size_per_gpu
    log_prob_micro_batch_size_per_gpu: null
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    ulysses_sequence_parallel_size: ${actor_rollout_ref.actor.ulysses_sequence_parallel_size} # sp size

  rollout:
    name: vllm
    temperature: 0.6
    top_k: -1 # 0 for hf rollout, -1 for vllm rollout
    top_p: 1.0
    use_fire_sampling: False # https://arxiv.org/abs/2410.21236
    prompt_length: ${data.max_prompt_length}  # not use for opensource
    response_length: ${data.max_response_length}

    # for vllm rollout
    dtype: bfloat16 # should align with FSDP
    gpu_memory_utilization: 0.5
    ignore_eos: False
    enforce_eager: True
    free_cache_engine: True
    load_format: dummy_dtensor
    tensor_model_parallel_size: 2
    max_num_batched_tokens: 65536
    max_model_len: 38000
    seed: 1
    max_num_seqs: 1024
    log_prob_micro_batch_size: null # will be deprecated, use log_prob_micro_batch_size_per_gpu
    log_prob_micro_batch_size_per_gpu: null
    log_prob_use_dynamic_bsz: ${actor_rollout_ref.actor.use_dynamic_bsz}
    log_prob_max_token_len_per_gpu: ${actor_rollout_ref.actor.ppo_max_token_len_per_gpu}
    disable_log_stats: True
    enable_chunked_prefill: True # may get higher throughput when set to True. When activated, Please increase max_num_batched_tokens or decrease max_model_len.
    # for hf rollout
    do_sample: True
    # number of responses (i.e. num sample times)
    n: 2 # > 1 for grpo
    val_kwargs:
      # sampling parameters for validation
      top_k: -1 # 0 for hf rollout, -1 for vllm rollout
      top_p: 0.95
      temperature: 0.6
      n: 4
      do_sample: True # default eager for validation

reward_model:
  enable: False
  
custom_reward_function:
  path: /home/ianwu/code/verl-stable/projects/reasoning_cache/rewards/evaluator.py
  name: compute_score

algorithm:
  gamma: 1.0
  lam: 1.0
  adv_estimator: grpo
  use_kl_in_reward: False  # false for grpo, true for ppo
  kl_penalty: kl  # how to estimate kl divergence

reasoning_cache:
  max_summary_tokens: 2048
  max_thinking_tokens: 16384
  reasoning_prompt_path: /home/ianwu/code/verl-stable/projects/reasoning_cache/prompts/sum_e2e_reasoning_prompt.txt
  summarization_prompt_path: /home/ianwu/code/verl-stable/projects/reasoning_cache/prompts/sum_e2e_summarization_prompt.txt
  use_think_tags: True
  online_rollout_steps: 4
  online_rollout_n_samples: 1
  online_rollout_steps_val: 4
  online_rollout_n_samples_val: 4
  thinking_train_samples_per_online_rollout: 1
  summary_train_samples_per_online_rollout: 1
  omit_online_rollout_initial_thinking_step: False
  thinking_train_n_samples: 8
  summary_train_n_samples: 4
  thinking_reward_rollout_steps: 0
  summary_reward_rollout_steps: 0
  thinking_reward_n_samples: 4
  summary_reward_n_samples: 4
  save_rollouts: False
  use_train_state_counter: True
  # Replay buffer settings
  use_replay_buffer: False
  buffer_initial_path: null
  buffer_sample_summaries_per_problem: 1
  buffer_purge_existing_on_add: False 
  # Summary-free mode settings
  summary_free: False